language: node_js
node_js:
  _ "stable"
install:
  - npm install
env:
  global:
    - CC_TEST_REPORTER_ID=3a75dcb4c4cecc15938f6b9d85c5347dbe4e96a5663fb0fc2df9ec03539eabe7
script:
  - npm test
after_success:
  - npm run coveralls