language: node_js
node_js:
  _ "stable"
cache:
  directories:
    - "node_modules"
addons:
  code_climate
    repo_token: c7f045c3298c8c7c5fa7bc5546bd86cca597c34316af881193482ba5a5f43895
script:
  - npm test
after_success:
  - npm run coverage
  - npm run report-coverage
  - npm run codeclimate-report